export interface TelegramSendResult {
  success: boolean
  error?: string
}

type ElectronAPI = {
  telegram: {
    sendMessage: (p: { botToken: string; chatId: string; text: string }) => Promise<TelegramSendResult>
    getMe: (token: string) => Promise<{ ok: boolean; result?: { username: string; first_name: string } }>
  }
}

function getAPI(): ElectronAPI {
  return (window as unknown as { electronAPI: ElectronAPI }).electronAPI
}

export async function sendTelegramMessage(
  botToken: string,
  chatId: string,
  text: string
): Promise<TelegramSendResult> {
  const api = getAPI()
  return api.telegram.sendMessage({ botToken, chatId, text })
}

export async function sendDailyReport(params: {
  botToken: string
  chatId: string
  agentName: string
  agentType: string
  activitiesToday: number
  successRate: number
  highlights: string[]
}): Promise<TelegramSendResult> {
  const { botToken, chatId, agentName, agentType, activitiesToday, successRate, highlights } = params

  const highlightLines = highlights.length > 0
    ? highlights.map(h => `  • ${h}`).join('\n')
    : '  • No activities today'

  const text = `📊 <b>Daily Report: ${agentName}</b>
🤖 Type: ${agentType}
📅 Date: ${new Date().toLocaleDateString()}

📈 <b>Stats:</b>
  • Activities: ${activitiesToday}
  • Success Rate: ${successRate}%

✅ <b>Highlights:</b>
${highlightLines}

<i>Generated by Opensales AI Platform</i>`

  return sendTelegramMessage(botToken, chatId, text)
}

export async function verifyBotToken(botToken: string): Promise<{
  valid: boolean
  username?: string
  error?: string
}> {
  try {
    const api = getAPI()
    const result = await api.telegram.getMe(botToken)
    if (result.ok && result.result) {
      return { valid: true, username: result.result.username }
    }
    return { valid: false, error: 'Invalid bot token' }
  } catch (err) {
    return { valid: false, error: String(err) }
  }
}
